export const DEFAULT_INSTRUMENTS = [
  { value: 'organ', label: 'Organ' },
  { value: 'piano', label: 'Piano' },
  { value: 'harpsichord', label: 'Harpsichord' },
  { value: 'strings', label: 'Strings' },
  { value: 'cello', label: 'Cello' },
  { value: 'harp', label: 'Harp' },
  { value: 'flute', label: 'Flute' },
  { value: 'clarinet', label: 'Clarinet' },
  { value: 'oboe', label: 'Oboe' },
  { value: 'saxophone', label: 'Saxophone' },
  { value: 'trumpet', label: 'Trumpet' },
  { value: 'brass', label: 'Brass' },
  { value: 'choir', label: 'Choir' },
  { value: 'pad', label: 'Pad' },
  { value: 'bells', label: 'Bells' },
  { value: 'celeste', label: 'Celeste' },
  { value: 'vibraphone', label: 'Vibraphone' },
  { value: 'marimba', label: 'Marimba' },
  { value: 'pluck', label: 'Pluck' },
  { value: 'bass', label: 'Bass' },
  { value: 'sonicBassResonant', label: 'Sonic Bass Resonant' },
  { value: 'clean', label: 'Clean' },
  { value: 'electric', label: 'Electric' },
  { value: 'distortion', label: 'Distortion' },
  { value: 'synth', label: 'Synth' },
];